#!/usr/bin/perl -w

# This script is written by HikariKnight and is free to use and modify
# as it fit you within the rules of RuneScape, it is based on 
# Ethoxyethaan's forum post on RuneScape showing how to use the files 
# from the Windows client to run it through the command line but with 
# limited functionality. I wrote this perl script in an attempt to port 
# the RuneScape client to linux and all other unix systems capable of 
# running java, the script also implement language settings support and 
# can be updated by replacing the bin/jagexappletviewer.jar and settings/runescape.prm
# with the ones found in the Windows client.

# This script is free to use and redistribute(as long credits are kept)
# If you like this script you may want to check out my other projects at
# http://hkprojects.weebly.com

my $scriptversion = "3.9.2";

# Before starting show runescape script version
print "RuneScape Unix Client script version $scriptversion\n\n";

# Use FindBin module to get script directory
use FindBin;
# Get script directory
my $cwd = $FindBin::RealBin;

# Include perl modules in ./modules
use lib $FindBin::RealBin."/modules";
require rsu_modules;

# Create a variable to store mutators inside for use as
# transport of information through module functions
my $rsu_data = {};
bless $rsu_data;

# Create mutators and add them to the variable
$rsu_data->create_mutator(qw(version OS cwd clientdir javabin javaversion HOME args verboseprms preferredjava forcealsa prmfile fallbackprms));

# Add clientdir data to the data container
$rsu_data->clientdir = $cwd;
# Add cwd data to the data container
$rsu_data->cwd = $cwd;
# Add scriptversion to the data container
$rsu_data->version = $scriptversion;
# Add all the arguments passed to the script to the data container
$rsu_data->args = "@ARGV";

# Detect the current OS and add it to the data container
$rsu_data->OS = "$^O";

# Get the environment variable for USERPROFILE
$rsu_data->HOME = $ENV{"HOME"};

# Make a variable to contain the location of the homefolder for use later in the script
my $HOME = $rsu_data->HOME;

# If --help was provided then print out the help text
if ($rsu_data->args =~ /--help/)
{
	# Display the help text
	print "Run the \"runescape\" script without any parameters to launch the client normally.
There are however some parameters you can use to alter
the behaviour of the script.

CHANGE PRM:
   You can change the runescape.prm file when running the runescape script:
	  runescape --prmfile=/path/to/prm.prm

VERBOSE MODES (warning: outputs a lot of text):
   Make java display full verbose output: 
      runescape --verbose
	
   Make java display selected verbose outputs (jni, gc and class verbose)
      runescape --verbose:jni
      runescape --verbose:gc
      runescape --verbose:class
   
   All 3 of the above verbose modes can be used together like this.
      runescape --verbose:gc --verbose:jni
		
   Save verbose output to a file:
   Simply add \"&> \$HOME/verbose.txt\" at the end of the command like this.
      runescape --verbose &> \$HOME/verbose.txt
      runescape --verbose:class --verbose:jni &> \$HOME/verbose.txt
      
   The file verbose.txt in your homefolder will then contain all the output.\n";
	exit;	
}

# If this script have been installed systemwide
if ($rsu_data->cwd =~ /^(\/usr\/s?bin|\/opt\/runescape|\/usr\/local\/s?bin|\/usr\/share)/)
{
	# Print debug info
	print "The script is running from a system path!\n".$rsu_data->HOME."/.config/runescape will be used as client folder instead!\n\n";
		
	# Change clientdir to ~/.config/runescape
	$rsu_data->clientdir = $rsu_data->HOME."/.config/runescape/";
		
	# Make the client folders
	system "mkdir -p \"".$rsu_data->HOME."/.config/runescape/bin\" && mkdir -p \"".$rsu_data->HOME."/.config/runescape/settings\"";
		
	# Symlink or Copy needed resources to the clientdir
	system "cp -v \"".$rsu_data->cwd."/settings/settings.conf\" \"".$rsu_data->clientdir."/settings/settings.conf\" && cp -v \"".$rsu_data->cwd."/settings/runescape.prm\" \"".$rsu_data->clientdir."/settings/runescape.prm\"";
	
	# Make a variable to contain the clientdir so we can use it in a command
	my $clientdir = $rsu_data->clientdir;
	
	# Check if runescape.prm exists
	my $prmfile_exists = `ls -la $clientdir/share|grep -P \"runescape.prm\$\"`;
		
	# If runescape.prm does not exist
	if ($prmfile_exists !~ /runescape.prm/)
	{
		# Copy the example file to clientdir as runescape.prm
		system "cp -v \"".$rsu_data->cwd."/settings/runescape.prm.example\" \"".$rsu_data->clientdir."/settings/runescape.prm\"";
	}
		
}
# Else if script is installed locally
elsif($rsu_data->cwd =~ /$HOME\/.local\/bin/)
{
	# Print debug info
	print "We are running from ".$rsu_data->cwd.", however the client\nshould be at \\\$HOME/.local/share/runescape\nchanging directory to \\\$HOME/.local/share/runescape\n\n";
		
	# change cwd to the local installation location
	$cwd = $rsu_data->HOME."/.local/opt/runescape";
}

# Due to legal reasons the file jagexappletviewer.jar is no longer included by default so we need to check if it exists
# If jagexappletviewer.jar do not exist inside the $rsu_data->cwd/bin folder then
rsu_cfjav::check_for_jagexappletviewer($rsu_data);

	
# Print debug info
print "Trying to read ".$rsu_data->clientdir."/settings/settings.conf\n";

########################################################################
#        BELOW THIS LINE ARE SOME SETTINGS YOU CAN CHANGE              #
#       PLEASE CHANGE THEM IN THE settings/settings.conf FILE          #
########################################################################

# Read the preferred java in the config file, if nothing is found then use default-java
$rsu_data->preferredjava = parseargs("preferredjava", "default-java");

# Read from the config file or passed parameters if the user want to tell java to use alsa in the base for sounds
# If nothing is found then do not use alsa and instead use the java default
$rsu_data->forcealsa = parseargs("forcealsa", "0");

# Check if a prmfile setting is active
$rsu_data->prmfile = parseargs("prmfile", "runescape.prm");

# Define fallbackprms incase we cannot read settings/runescape.prm
$rsu_data->fallbackprms = "jagexappletviewer.jar -Dsun.java2d.noddraw=true -Dcom.jagex.config=http://www.runescape.com/k=3/l=\$(Language:0)/jav_config.ws -Xss2m -Xmx512m -XX:CompileThreshold=1500 -Xincgc -XX:+UseConcMarkSweepGC -XX:+UseParNewGC jagexappletviewer ";

########################################################################
#DO NOT EDIT THE CODE BELOW THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING!
########################################################################

# Make debug info look abit nicer
print "\n";

# Check if any --verbose parameters were passed to the script
$rsu_data->verboseprms = rsu_verbose::verbosecheck($rsu_data);

# Make debug info look abit nicer
print "\n";

# Be strict to avoid messy code
use strict;

# Start actual process of running the client

# Run the main function for unix
rsu_mains::unix_main($rsu_data);

#
#---------------------------------------- *** ----------------------------------------
#

sub parseargs
{
	# Get the variables passed to the function
	my ($arg2find, $default) = @_;
	
	# If a prmfile is passed to the script from the terminal then
	if ("@ARGV" =~ /(-|--)$arg2find=/)
	{
		# For each parameter found in @ARGV
		foreach my $arg (@ARGV)
		{
			# If the parameter matches the one we are looking for
			if ($arg =~ /(-|--)$arg2find=/)
			{
				# Split the parameter by =
				my @prmname = split /=/, $arg;
				
				# Return the setting found in the parameter
				return "$prmname[1]";
			}
		}	
	}
	else
	{
		# If no parameter that matches is passed then read from settings.conf
		my $result = rsu_IO::readconf("$arg2find", "$default", $rsu_data);
		
		# Return setting
		return $result;
	}
}

#
#---------------------------------------- *** ----------------------------------------
#

# Create mutator function from "Programming Perl"
sub create_mutator
{
	my $self = shift;

	# From "Programming Perl" 3rd Ed. p338.
	for my $attribute (@_)
	{
		no strict "refs"; # So symbolic ref to typeglob works.
		no warnings;      # Suppress "subroutine redefined" warning.

		*$attribute = sub : lvalue
		{
			my $self = shift;

			$self->{$attribute} = shift if @_;
			$self->{$attribute};
		};
	}
}

#
#---------------------------------------- *** ----------------------------------------
#

__END__
